'Category: CI':
-   .github/workflows/*
'Category: PyLavPlayer':
-   audio/*
'Category: PyLavConfigurator':
-   plconfig/*
'Category: PyLavEffects':
-   pleffects/*
'Category: PyLavLocalFiles':
-   pllocal/*
'Category: PyLavLyrics':
-   pllyrics/*
'Category: PyLavManagedNode':
-   plmanagednode/*
'Category: PyLavMigrator':
-   plmigrator/*
'Category: PyLavNodes':
-   plnodes/*
'Category: PyLavNotifier':
-   plnotifier/*
'Category: PyLavPlaylists':
-   plplaylists/*
'Category: PyLavRadio':
-   plradio/*
'Category: PyLavUtils':
-   plutils/*
'Category: Admin':
-   tools/*
-   .github/*
-   .pre-commit-config.yaml
-   crowdin.yml
-   pyproject.toml
-   README.md
-   info.json
-   CODE_OF_CONDUCT.md
-   LICENSE
-   CLA.md
-   CONTRIBUTING.md
-   .sourcery.yaml
'Category: i18n':
-   /**/locales/*
