project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_KEY
base_path: ./
preserve_hierarchy: true
commit_message: '[skip ci] Update translations'
files:
-   source: audio/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plconfig/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: pleffects/**/messages.pot
    translation: /%original_path%/%locale%.poo
-   source: pllocal/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plmanagednode/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plmigrator/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plnodes/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plnotifier/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plplaylists/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plradio/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: plutils/**/messages.pot
    translation: /%original_path%/%locale%.po
-   source: pllyrics/**/messages.pot
    translation: /%original_path%/%locale%.po
