project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_KEY
base_path: ./
preserve_hierarchy: true
commit_message: Update translations
files:
-   source: /**/messages.pot
    translation: /%original_path%/%locale%.po
    dest: cogs/%original_path%/messages.pot
    ignore:
    -   tools/**/*.*
    -   .github/**/*.*
