name: Auto Merge Translations
on:
    pull_request:
        types:
        -   opened
        -   labeled
        -   edited
        -   reopened
        -   synchronize
        -   ready_for_review
        -   unlocked
        -   review_request_removed
    pull_request_review:
        types:
        -   submitted
        -   edited
jobs:
    automerge:
        runs-on: [self-hosted, linux, x64]
        steps:
        -   id: automerge
            name: automerge
            uses: pascalgn/automerge-action@v0.15.5
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MERGE_FORKS: 'false'
                MERGE_METHOD: squash
                UPDATE_METHOD: rebase
                MERGE_REQUIRED_APPROVALS: '0'
                MERGE_METHOD_LABELS: automerge=merge,autosquash=automerge
                MERGE_COMMIT_MESSAGE: Auto Merge
                MERGE_REMOVE_LABELS: automerge
                MERGE_LABELS: automerge
                MERGE_FILTER_AUTHOR: github-actions[bot]
                MERGE_METHOD_LABEL_REQUIRED: true
                MERGE_DELETE_BRANCH: true
