name: Auto Labeler - PRs
on:
    pull_request_target:
        types:
        -   opened
        -   synchronize
        -   reopened
        -   labeled
        -   unlabeled
permissions:
    pull-requests: write

jobs:
    build:
        runs-on: [self-hosted, linux, x64]
        steps:
        -   name: Apply Type Label
            uses: actions/labeler@v4
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                sync-labels: '' # this is a temporary workaround, see #4844
