name: Pre-commit & Sourcery
on:
    pull_request:
    push:
        branches:

permissions:
    pull-requests: write

jobs:
    run:
        name: Pre-commit fixes & Sourcery
        runs-on: [self-hosted, linux, x64]
        steps:
        -   uses: actions/checkout@v3.3.0
        -   uses: actions/setup-python@v4
            with:
                python-version: '3.11'
        -   uses: pre-commit/action@v3.0.0
            env:
                SKIP: sourcery
        -   uses: pre-commit-ci/lite-action@v1.0.1
            if: always()
